### ISSUE TITLE
Does not Support Source File Running

### ISSUE THREAD

**Issue by jimzhan** [kardianos/osext#2]
``` sh
go run server.go
```

can only fetch the temporary executable

``` sh
/private/var/folders/g7/psb64vj106321f1k80jj1frc0000gn/T/go-build519666050/command-line-arguments/_obj/exe/serve
```

**Comment by dmitshur** [comment]
That is the actual executable which is running. What would you expect instead?

**Comment by jimzhan** [comment]
I think it'll be better to distinglish between the actual binary executable & direct source running (tmp. executable), or at least make it optional, its crucial for accessing relative resource in the same folder. (BTW, I use runtime.Caller(2) in my own framework for both now)

**Comment by kardianos** [comment]
Hi @jimzhan,
Thank you for your report. The call "Executable" gets the running executable. In the case of "go run", the current working directory is probably what you want. I don't know of a way to distinguish between a executable compiled with "go run" and one that wasn't. As such I don't know of a way to get what you're looking for.

If you can write some code that demonstrates the desired behavior, we can talk about the potential to integrate. Otherwise this looks like a programming error on your part.

-Daniel
